// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYzklxnFY6ampOOsGtw1p3V_9PDjXLvoY',
    appId: '1:909500262225:web:aa49b84e0da354a7c6d570',
    messagingSenderId: '909500262225',
    projectId: 'ecommerce-flu-9e6cf',
    authDomain: 'ecommerce-flu-9e6cf.firebaseapp.com',
    storageBucket: 'ecommerce-flu-9e6cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADcctjswFngocyR1HhL9NXYJPlCWaMAeM',
    appId: '1:909500262225:android:d1b213b4072aac2dc6d570',
    messagingSenderId: '909500262225',
    projectId: 'ecommerce-flu-9e6cf',
    storageBucket: 'ecommerce-flu-9e6cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwwS70pZMg_HC32dG5eZd0x8SZxT0e70',
    appId: '1:909500262225:ios:3dc1f89916c78e39c6d570',
    messagingSenderId: '909500262225',
    projectId: 'ecommerce-flu-9e6cf',
    storageBucket: 'ecommerce-flu-9e6cf.appspot.com',
    iosBundleId: 'com.example.fluttertestux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwwS70pZMg_HC32dG5eZd0x8SZxT0e70',
    appId: '1:909500262225:ios:56cedb11c1b337c9c6d570',
    messagingSenderId: '909500262225',
    projectId: 'ecommerce-flu-9e6cf',
    storageBucket: 'ecommerce-flu-9e6cf.appspot.com',
    iosBundleId: 'com.example.fluttertestux.RunnerTests',
  );
}
